export const GlobalFileNames = {
	apiConversationHistory: "api_conversation_history.json",
	uiMessages: "ui_messages.json",
	glamaModels: "glama_models.json",
	openRouterModels: "openrouter_models.json",
	requestyModels: "requesty_models.json",
	mcpSettings: "mcp_settings.json",
	unboundModels: "unbound_models.json",
	customModes: "custom_modes.json",
	anthropicModels: "anthropic_models.json",
	bedrockModels: "bedrock_models.json",
	vertexModels: "vertex_models.json",
	geminiModels: "gemini_models.json",
	mistralModels: "mistral_models.json",
	deepseekModels: "deepseek_models.json",
	ollamaModels: "ollama_models.json",
	lmStudioModels: "lmstudio_models.json",
	vsCodeLmModels: "vscode_lm_models.json",
	openAiModels: "openai_models.json",
}
